### ISSUE TITLE
Today installed the spotify-ffmpeg as dependencies.

### ISSUE THREAD

**Issue by upfringe** [negativo17/spotify-ffmpeg#1]
What does it do actually?
What was the problem before?

**Comment by scaronni** [comment]
I guess you are on Fedora with the multimedia repository enabled.

Spotify requires an FFMpeg version (max 4.x) to playback local files also across devices.

There is this rich dependency in the package:

https://github.com/negativo17/spotify-client/blob/master/spotify-client.spec#L50

It's there in case you want to use the spotify repository without using the multimedia one.

I changed the dependency recentrly from `ffmpeg-libs` to `libavcodec58` and `libavformat58`, but this means something is not working. Can you try doing the following?

`dnf remove spotify-ffmpeg`

Thanks.

**Comment by upfringe** [comment]
After i installed spotify-ffmpeg the spotify seems to use less resources than before i don't know what happened but it works...
